name: Primeirao
on:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  hello:
    container: docker:stable
    services:
      docker:
        image: docker:stable
        run: dokcer:dind
         
    steps:
    
    - name: Hello World
      run: echo -e " Helloooooo  World! "



