name: Primeirao
on:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  hello:
    runs-on: ubuntu-latest
    container: docker:stable

    services:
      docker:
        image: docker:stable
         
    steps:
    - name: Build imagem docker
#      run: docker build -t minha-imagem .
      run: cat /__w/runners/runners/Dockerfile
    
    - name: Hello World
      run: echo -e " Helloooooo  World! "



