name: Primeirao
on:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  hello:
    
    runs-on: ubuntu-latest
    container: docker:stable

    services:
      docker:
        image: docker:stable
         
    steps:
      working-directory: runners
    - name: Build imagem docker
      run: docker build -t minha-imagem .
    
    - name: Hello World
      run: echo -e " Helloooooo  World! "



